server.port : 8010

spring:
  application:
    name: feign-integration

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: basic
      user-service:
        connectTimeout: 6000
        readTimeout: 6000
        loggerLevel: FULL
        decode404: false


logging:
  level:
    com.nirajtailor.feignintegration.Proxy: DEBUG